name: API Request Every Hour

on:
  schedule:
    - cron: '0 * * * *'  # Every hour
  workflow_dispatch:

jobs:
  request_job:
    runs-on: ubuntu-latest
    # Add permissions to enable pushing with GITHUB_TOKEN
    permissions:
      contents: write

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Install Python packages
      run: pip install requests pandas

    - name: Make API request and save CSV
      env:
        CLIENT_ID: ${{ secrets.CLIENT_ID }}
        CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
      run: python script/request.py

    - name: Commit and Push updated CSV
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add data/stations.csv
        git commit -m "Update stations.csv [bot]" || echo "No changes to commit"
        git push origin HEAD:main